# Generated by Django 2.0.2 on 2018-04-29 13:43

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20180305_2252'), ('core', '0003_auto_20180307_0139'), ('core', '0004_auto_20180307_0146'), ('core', '0005_photo'), ('core', '0006_auto_20180310_1341'), ('core', '0007_remove_photo_country'), ('core', '0008_playlist_video'), ('core', '0009_auto_20180310_2016'), ('core', '0010_auto_20180310_2135'), ('core', '0011_auto_20180312_2215'), ('core', '0012_auto_20180312_2219'), ('core', '0013_auto_20180312_2233'), ('core', '0014_auto_20180312_2235'), ('core', '0015_player_team'), ('core', '0016_remove_team_players'), ('core', '0017_player_team'), ('core', '0018_circuit'), ('core', '0019_auto_20180317_0330'), ('core', '0020_auto_20180317_0337'), ('core', '0021_auto_20180428_1523'), ('core', '0022_auto_20180428_1553'), ('core', '0023_player_country'), ('core', '0024_auto_20180428_1759')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='título')),
                ('image', cloudinary.models.CloudinaryField(help_text='Imagem com: 873 X 1280 pixels', max_length=255, verbose_name='imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='nome')),
                ('link', models.CharField(max_length=250)),
                ('logo', cloudinary.models.CloudinaryField(help_text='Imagem com: 350 X 350 pixels', max_length=255, verbose_name='logotipo')),
                ('position', models.IntegerField(default=0, verbose_name='posição')),
            ],
            options={
                'verbose_name': 'patrocinador',
                'verbose_name_plural': 'patrocinadores',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SpecialParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='nome')),
                ('image', cloudinary.models.CloudinaryField(help_text='Imagem com: 300 X 300 pixels', max_length=255, verbose_name='imagem')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='país')),
            ],
            options={
                'verbose_name': 'participação especial',
                'verbose_name_plural': 'participações especiais',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='título')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
            },
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='título')),
                ('code', models.CharField(blank=True, max_length=60, null=True, verbose_name='código')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='código')),
                ('play_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlayList')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'jogador',
                'verbose_name_plural': 'jogadores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='nome')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, help_text='Imagem com: 350 X 350 pixels', max_length=255, null=True, verbose_name='logotipo')),
            ],
            options={
                'verbose_name': 'time',
                'verbose_name_plural': 'times',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Team'),
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, unique=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'circuito',
                'verbose_name_plural': 'circuitos',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='posição')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Player')),
            ],
            options={
                'ordering': ('tournament', 'position'),
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, unique=True, verbose_name='descrição')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Circuit', verbose_name='circuito')),
                ('players', models.ManyToManyField(through='core.Ranking', to='core.Player')),
            ],
            options={
                'verbose_name': 'torneio',
                'verbose_name_plural': 'torneios',
                'ordering': ('description',),
            },
        ),
        migrations.AddField(
            model_name='ranking',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('tournament', 'position')},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ('tournament', 'position'), 'verbose_name': 'classificação', 'verbose_name_plural': 'classificações'},
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(default='BR', max_length=2, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Team', verbose_name='time'),
        ),
    ]
