# Generated by Django 2.0.2 on 2018-03-05 21:39

from django.db import migrations, models
import versatileimagefield.fields
import vivalviar.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('image', versatileimagefield.fields.VersatileImageField(help_text='Imagem com: 300 X 300 pixels', verbose_name='imagem')),
            ],
        ),
    ]
