# Generated by Django 2.0.2 on 2018-03-05 22:52

from django.db import migrations, models
import versatileimagefield.fields
import vivalviar.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nome')),
                ('link', models.CharField(max_length=250)),
                ('logo', versatileimagefield.fields.VersatileImageField(help_text='Imagem com: 350 X 350 pixels', verbose_name='logotipo')),
                ('position', models.IntegerField(default=0, verbose_name='posição')),
            ],
            options={
                'verbose_name': 'patrocinador',
                'verbose_name_plural': 'patrocinadores',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(help_text='Imagem com: 800 X 800 pixels', verbose_name='imagem'),
        ),
    ]
