# Generated by Django 2.0.2 on 2018-03-07 01:39

from django.db import migrations, models
import versatileimagefield.fields
import vivalviar.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180305_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='nome')),
                ('image', versatileimagefield.fields.VersatileImageField(help_text='Imagem com: 300 X 300 pixels', verbose_name='imagem')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='país')),
            ],
            options={
                'verbose_name': 'participação especial',
                'verbose_name_plural': 'participações especiais',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='nome'),
        ),
    ]
