# Generated by Django 2.0.2 on 2018-05-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180502_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('O', 'Online'), ('P', 'Presencial')], default='O', max_length=1, verbose_name='tipo'),
        ),
    ]
