# Generated by Django 2.0.2 on 2018-03-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180307_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialparticipation',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='país'),
        ),
    ]
