# Generated by Django 2.0.2 on 2018-05-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180502_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Circuit', verbose_name='circuito'),
        ),
    ]
