# Generated by Django 2.0.2 on 2018-03-10 13:38

from django.db import migrations, models
import versatileimagefield.fields
import vivalviar.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180307_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='título')),
                ('image', versatileimagefield.fields.VersatileImageField(verbose_name='imagem')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='país')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
