# Generated by Django 2.0.2 on 2018-03-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('title',), 'verbose_name': 'foto', 'verbose_name_plural': 'fotos'},
        ),
    ]
