# Generated by Django 2.0.2 on 2018-05-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180512_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='score_by_team',
            field=models.BooleanField(default=False, verbose_name='pontuação por time'),
        ),
    ]
