# Generated by Django 2.0.2 on 2018-03-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180310_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='country',
        ),
    ]
