# Generated by Django 2.0.2 on 2018-03-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_photo_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='título')),
                ('code', models.CharField(blank=True, max_length=60, null=True, verbose_name='código')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='código')),
                ('play_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlayList')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
