# Generated by Django 2.0.2 on 2018-03-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_playlist_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
