# Generated by Django 2.0.2 on 2018-03-12 22:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180312_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Imagem com: 873 X 1280 pixels', max_length=255, verbose_name='imagem'),
        ),
    ]
