# Generated by Django 2.0.2 on 2018-03-17 02:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180312_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'jogador',
                'verbose_name_plural': 'jogadores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='nome')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, help_text='Imagem com: 350 X 350 pixels', max_length=255, null=True, verbose_name='logotipo')),
                ('players', models.ManyToManyField(to='core.Player', verbose_name='jogadores')),
            ],
            options={
                'verbose_name': 'time',
                'verbose_name_plural': 'times',
                'ordering': ('name',),
            },
        ),
    ]
