# Generated by Django 2.0.2 on 2018-03-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, unique=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'circuito',
                'verbose_name_plural': 'circuitos',
                'ordering': ('description',),
            },
        ),
    ]
