# Generated by Django 2.0.2 on 2018-03-17 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_circuit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='posição')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Player')),
            ],
            options={
                'ordering': ('tournament', 'position'),
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, unique=True, verbose_name='descrição')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Circuit')),
                ('players', models.ManyToManyField(through='core.Ranking', to='core.Player')),
            ],
            options={
                'verbose_name': 'torneio',
                'verbose_name_plural': 'torneios',
                'ordering': ('description',),
            },
        ),
        migrations.AddField(
            model_name='ranking',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('tournament', 'position')},
        ),
    ]
