# Generated by Django 2.0.2 on 2018-04-28 15:23

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180317_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='nome')),
                ('flag', cloudinary.models.CloudinaryField(blank=True, help_text='Imagem com: 250 X 250 pixels', max_length=255, null=True, verbose_name='bandeira')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Country'),
        ),
    ]
