# Generated by Django 2.0.2 on 2018-04-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180428_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
