# Generated by Django 2.0.2 on 2018-04-28 15:55

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180428_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(default='BR', max_length=2, verbose_name='país'),
        ),
    ]
